# Pydantic ToolPlan model for validating LLM JSON outputs as well as storing data classes.
from pydantic import BaseModel
from typing import Literal
from dataclasses import dataclass, field

class ToolPlan(BaseModel):
    name: str
    args: dict = {}

class PlannerOutput(BaseModel):
    reasoning: str
    path: Literal["no_tools", "tools"]
    tools: list[ToolPlan] = []

# For SQL selector
class SQLPlan(BaseModel):
    queries: list[str]

class CourseDetailsPlan(BaseModel):
    location: str
    race: str
    query: str
    details: str

class EndBehaviorClassification(BaseModel):
    end_conversation: bool
    
class AskRequest(BaseModel):
    query: str
    session_id: str # generated by front end per session

class DataRequest(BaseModel):
    start_date: str = None
    end_date: str = None

class RaceRequest(BaseModel):
    race_description: str = None
    goal_time: str = None
    race_distance_miles: float = None
    race_date: str = None

class PreferencesRequest(BaseModel):
    days_per_week: int = None
    preferred_days: list = None
    avg_miles: float = None
    max_miles: float = None
    time_based: bool = None

class PlanInterval(BaseModel):
    interval_num: int
    interval_type: Literal["WARMUP", "WORK", "REST", "COOLDOWN"]
    distance: str = None       # e.g. "400m", "1mi"
    target_pace: str = None    # e.g. "7:00/mi"
    duration: str = None       # e.g. "10min" — alternative to distance
    rest_duration: str = None  # e.g. "90sec jog"
    notes: str = None

class PlanDay(BaseModel):
    plan_date: str             # YYYY-MM-DD
    week_number: int
    day_of_week: Literal["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"]
    workout_type: Literal["EASY", "LONG", "TEMPO", "INTERVAL", "REST", "CROSS"]
    target_miles: float = None
    target_pace: str = None
    notes: str = None
    intervals: list[PlanInterval] = []

@dataclass    
class History:
    summary: str = ""
    recent: list[dict] = field(default_factory=list)
    turn_count: int = 0





