# Pydantic ToolPlan model for validating LLM JSON outputs as well as storing data classes.
from dataclasses import dataclass, field
from typing import Literal, Optional

from pydantic import BaseModel


class ToolPlan(BaseModel):
    name: str
    args: dict = {}


class PlannerOutput(BaseModel):
    reasoning: str
    path: Literal["no_tools", "tools"]
    tools: list[ToolPlan] = []


# For SQL selector
class SQLPlan(BaseModel):
    queries: list[str]


class CourseDetailsPlan(BaseModel):
    location: str
    race: str
    query: str
    details: str


class RaceRegistrationInfo(BaseModel):
    registration_timeline: Optional[str] = None
    qualifying_times: Optional[str] = None
    registration_methods: Optional[str] = None
    registration_costs: Optional[str] = None
    corral_details: Optional[str] = None
    additional_details: Optional[str] = None


class RaceDayInfo(BaseModel):
    start_time: Optional[str] = None
    start_location: Optional[str] = None
    corral_details: Optional[str] = None
    additional_details: Optional[str] = None


class RaceInfoPlan(BaseModel):
    info_type: Literal["registration", "race_day"]
    info: RaceRegistrationInfo | RaceDayInfo
    race: str
    location: str


class EndBehaviorClassification(BaseModel):
    end_conversation: bool


class AskRequest(BaseModel):
    query: str
    session_id: str  # generated by front end per session
    has_plan: bool = False
    location: str = "New York, NY"
    today: str = None


class DataRequest(BaseModel):
    start_date: str = None
    end_date: str = None


class RaceRequest(BaseModel):
    race_description: str = None
    goal_time: str = None
    race_distance_miles: float = None
    race_date: str = None


class UserInfoRequest(BaseModel):
    name: str = None
    theme: str = None
    location: str = None


class PreferencesRequest(BaseModel):
    days_per_week: int = None
    preferred_days: list = None
    avg_miles: float = None
    max_miles: float = None
    time_based: bool = None
    notes: str = None


class PlanInterval(BaseModel):
    interval_num: int
    interval_type: Literal["WARMUP", "WORK", "REST", "COOLDOWN"]
    distance: str | None = None
    target_pace: str | None = None
    duration: str | None = None
    rest_duration: str | None = None
    notes: str | None = None


class PlanDay(BaseModel):
    plan_date: str
    week_number: int
    day_of_week: Literal["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"]
    workout_type: Literal["EASY", "LONG", "TEMPO", "INTERVAL", "REST", "CROSS"]
    target_miles: float | None = None
    target_pace: str | None = None
    notes: str | None = None
    intervals: list[PlanInterval] = []


class PlanChange(BaseModel):
    plan_date: str
    workout_type: Literal["EASY", "AEROBIC", "LONG", "TEMPO", "INTERVAL", "STRENGTH", "REST", "CROSS"]
    target_miles: float | None = None
    target_pace: str | None = None
    notes: str | None = None
    intervals: list[PlanInterval] | None = None


class UpdatePlanOutput(BaseModel):
    changes: list[PlanChange]


class PatchDayRequest(BaseModel):
    workout_type: str = None
    target_miles: float = None
    target_pace: str = None
    notes: str = None
    intervals: list[PlanInterval] | None = None


class SyncPlanRequest(BaseModel):
    today: str = None


@dataclass
class History:
    summary: str = ""
    recent: list[dict] = field(default_factory=list)
    turn_count: int = 0


class LoginRequest(BaseModel):
    email: str
    password: str


class GarminCredentials(BaseModel):
    email: str
    password: str
