# Pydantic ToolPlan model for validating LLM JSON outputs as well as storing data classes.
from pydantic import BaseModel
from typing import Literal
from dataclasses import dataclass, field

class ToolPlan(BaseModel):
    name: str
    args: dict = {}

class PlannerOutput(BaseModel):
    reasoning: str
    path: Literal["no_tools", "tools"]
    tools: list[ToolPlan] = []

# For SQL selector
class SQLPlan(BaseModel):
    queries: list[str]

class CourseDetailsPlan(BaseModel):
    location: str
    race: str
    query: str
    details: str

class EndBehaviorClassification(BaseModel):
    end_conversation: bool
    
class AskRequest(BaseModel):
    query: str
    session_id: str # generated by front end per session

class DataRequest(BaseModel):
    start_date: str = None
    end_date: str = None

@dataclass    
class History:
    summary: str = ""
    recent: list[dict] = field(default_factory=list)
    turn_count: int = 0





